- name: Install compose cli
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: "/usr/bin/docker"
    mode: '0755'

- name: Create App Folder
  become: true
  ansible.builtin.file:
    path: /app
    state: directory
    owner: ar3m
    group: ar3m
    mode: '0644'

- name: Get ar3m app from main
  become: true
  git:
    repo: https://github.com/mlargeot/Area.git
    dest: /app/Area
    version: main

- name: Copy env files
  become: true
  copy:
    src: "{{ item }}"
    dest: /app/Area/env/
  loop:
    - /tmp/back.env
    - /tmp/mongo.env

- name: Change ownership of app files to ar3m
  become: true
  ansible.builtin.file:
    path: /app/Area
    state: directory
    owner: ar3m
    group: ar3m
    recurse: yes

- name: Deploy App
  become: true
  community.docker.docker_compose_v2:
    project_src: /app/Area/
    files:
      - /app/Area/docker-compose.prod.yml
    services:
      - db
      - server
      - client_web
    build: always
