- name: Create App Folder
  become: true
  ansible.builtin.file:
    path: /app
    state: directory
    owner: ar3m
    group: ar3m
    mode: '0644'

- name: Get ar3m app from main
  become: true
  git:
    repo: https://github.com/mlargeot/Area.git
    dest: /app/Area
    version: dev

- name: Copy env files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: /tmp/back.env, dest: /app/Area/env/ }
    - { src: /tmp/mongo.env, dest: /app/Area/env/ }
    - { src: /tmp/front.env, dest: /app/Area/frontend/.env }

- name: Change ownership of app files to ar3m
  become: true
  ansible.builtin.file:
    path: /app/Area
    state: directory
    owner: ar3m
    group: ar3m
    recurse: yes

- name: Deploy App
  become: true
  shell:
    cmd: "docker compose -f /app/Area/docker-compose.prod.yml up db server client_web --build -d"
