- name: Copy Docker Env Files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    # Env to copy
    #- { src: ../files/file_to_copy, dest: /dest_to_copy/, owner: owner, group: group, mode: file_mode }
