- name: Copy Docker Env Files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: ../files/back.env, dest: /tmp/, owner: ar3m, group: ar3m, mode: '0644' }
    - { src: ../files/mongo.env, dest: /tmp/, owner: ar3m, group: ar3m, mode: '0644' }
    - { src: ../files/front.env, dest: /tmp/, owner: ar3m, group: ar3m, mode: '0644' }
    - { src: ../files/expo.env, dest: /tmp/, owner: ar3m, group: ar3m, mode: '0644' }
