- name: Create necessary folders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    #- path_to_app_folder

- name: Copy python hook files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - {src: ../files/server.py, dest: path_to_dest, owner: ower, group: group, mode: '0644'}
    - {src: ../files/requirements.txt, dest: path_to_dest, owner: owner, group: group, mode: '0644'}
    - {src: ../files/flask.service, dest: path_to_dest, owner: ower, group: group, mode: '0644'}

- name: Create virtualenv
  become: true
  command:
    cmd: python3 -m venv path_to_venv
    creates: "path_to_venv"

- name: Install hooks requirements
  become: true
  pip:
    requirements: path_to_requirements
    virtualenv: path_to_venv
    extra_args: "--no-cache-dir"

- name: Reload systemd
  become: true
  command: systemctl daemon-reload

- name: Enable Flask service
  become: true
  systemd:
    name: flask
    enabled: yes

- name: Start Flask service
  become: true
  systemd:
    name: flask
    state: restarted
    daemon-reload: yes