- name: Create necessary folders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /home/ar3m/hooks
    - /home/ar3m/hooks/app

- name: Copy python hook files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - {src: ../files/server.py, dest: /home/ar3m/hooks/app, owner: ar3m, group: ar3m, mode: '0644'}
    - {src: ../files/requirements.txt, dest: /home/ar3m/hooks/, owner: ar3m, group: ar3m, mode: '0644'}
    - {src: ../files/flask.service, dest: /lib/systemd/system/, owner: root, group: root, mode: '0644'}

- name: Create virtualenv
  become: true
  command:
    cmd: python3 -m venv /home/ar3m/hooks/venvs
    creates: "/home/ar3m/hooks/venvs"

- name: Install hooks requirements
  become: true
  pip:
    requirements: /home/ar3m/hooks/requirements.txt
    virtualenv: /home/ar3m/hooks/venvs/
    extra_args: "--no-cache-dir"

- name: Reload systemd
  become: true
  command: systemctl daemon-reload

- name: Enable Flask service
  become: true
  systemd:
    name: flask
    enabled: yes

- name: Start Flask service
  become: true
  systemd:
    name: flask
    state: restarted
